#!/usr/bin/env python3
"""VisionforLife -> thegospel.kr/visionforlife FTP 배포."""

from __future__ import annotations

import json
import os
import shutil
import ftplib
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent
LOCAL = ROOT.parent / "thegospel-kr" / "visionforlife"
REMOTE = "/www/visionforlife"
PUBLIC_URL = "https://thegospel.kr/visionforlife/"

STATIC_FILES = [
    ".htaccess",
    "index.html",
    "app.js",
    "app.css",
    "sw.js",
    "manifest.json",
    "icon.svg",
    "icon-192.png",
    "icon-512.png",
    "visionforlife-icon-maskable-512.png",
    "apple-touch-icon.png",
    "markdown.js",
    "scr-link.js",
    "version.js",
    "api.php",
    "api.config.php",
]


def find_deploy_config() -> Path | None:
    base = Path(r"C:\Projects\bible-qna")
    if not base.is_dir():
        return None
    matches = list(base.rglob("deploy.config.json"))
    return matches[0] if matches else None


def collect_data_files() -> list[str]:
    files = ["data/catalogs.json"]
    bible_verses = ROOT / "bible" / "verses.json"
    if bible_verses.is_file():
        files.append("bible/verses.json")
    catalogs_dir = ROOT / "data" / "catalogs"
    if catalogs_dir.is_dir():
        for path in sorted(catalogs_dir.rglob("*.json")):
            rel = path.relative_to(ROOT).as_posix()
            if rel not in files:
                files.append(rel)
    courses_dir = ROOT / "data" / "courses"
    if courses_dir.is_dir():
        for path in sorted(courses_dir.rglob("mindmap.json")):
            files.append(path.relative_to(ROOT).as_posix())
        for path in sorted(courses_dir.rglob("*")):
            if path.is_file() and path.suffix.lower() in {".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg"}:
                files.append(path.relative_to(ROOT).as_posix())
    return files


def all_deploy_files() -> list[str]:
    return STATIC_FILES + collect_data_files()


def ensure_local_dir() -> None:
    LOCAL.mkdir(parents=True, exist_ok=True)


def sync_files(files: list[str]) -> list[str]:
    ensure_local_dir()
    synced: list[str] = []
    for rel in files:
        src = ROOT / rel.replace("/", os.sep)
        dst = LOCAL / rel.replace("/", os.sep)
        if not src.is_file():
            raise FileNotFoundError(f"Missing source file: {src}")
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        synced.append(rel)
    return synced


def ensure_dir(ftp: ftplib.FTP, path: str) -> None:
    parts = [p for p in path.split("/") if p]
    cur = ""
    for part in parts:
        cur += "/" + part
        try:
            ftp.mkd(cur)
        except ftplib.error_perm:
            pass


def upload_files(files: list[str]) -> dict:
    cfg_path = find_deploy_config()
    if not cfg_path:
        return {"ok": False, "error": "FTP 설정(deploy.config.json)을 찾을 수 없습니다"}

    if not LOCAL.is_dir():
        return {"ok": False, "error": "배포 로컬 폴더가 없습니다"}

    try:
        cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return {"ok": False, "error": f"FTP 설정 읽기 실패: {exc}"}

    uploaded: list[str] = []
    try:
        ftp = ftplib.FTP()
        ftp.connect(cfg["host"], cfg.get("port", 21), timeout=120)
        ftp.login(cfg["username"], cfg["password"])
        if cfg.get("usePassive", True):
            ftp.set_pasv(True)
        ensure_dir(ftp, REMOTE)
        for rel in files:
            local = LOCAL / rel.replace("/", os.sep)
            if not local.is_file():
                ftp.quit()
                return {"ok": False, "error": f"업로드 파일 없음: {rel}"}
            remote = REMOTE + "/" + rel.replace("\\", "/")
            ensure_dir(ftp, os.path.dirname(remote).replace("\\", "/"))
            with local.open("rb") as f:
                ftp.storbinary("STOR " + remote, f)
            uploaded.append(rel)
        ftp.quit()
    except (ftplib.Error, OSError, KeyError) as exc:
        return {"ok": False, "error": f"FTP 업로드 실패: {exc}", "files": uploaded}

    verify_ok = False
    try:
        with urllib.request.urlopen(PUBLIC_URL, timeout=30) as res:
            verify_ok = res.status == 200
    except OSError:
        pass

    return {
        "ok": True,
        "url": PUBLIC_URL,
        "files": uploaded,
        "verifyOk": verify_ok,
    }


def sync_api_config() -> None:
    """Write api.config.php from config.local.json adminPin before deploy."""
    cfg_path = ROOT / "config.local.json"
    pin = "4464572"
    required = True
    if cfg_path.is_file():
        try:
            cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
            pin = str(cfg.get("adminPin") or pin)
            required = bool(cfg.get("adminPinRequired", True))
        except (OSError, json.JSONDecodeError):
            pass
    pin_js = json.dumps(pin, ensure_ascii=False)
    required_js = "true" if required else "false"
    content = (
        "<?php\n"
        "/** Auto-generated by deploy_thegospel.py — do not commit secrets. */\n"
        "return [\n"
        f"  'adminPin' => {pin_js},\n"
        f"  'adminPinRequired' => {required_js},\n"
        "];\n"
    )
    (ROOT / "api.config.php").write_text(content, encoding="utf-8")


def deploy_to_thegospel(files: list[str] | None = None) -> dict:
    sync_api_config()
    files = list(files or all_deploy_files())
    try:
        sync_files(files)
    except FileNotFoundError as exc:
        return {"ok": False, "error": str(exc)}
    except OSError as exc:
        return {"ok": False, "error": f"로컬 동기화 실패: {exc}"}
    return upload_files(files)


def deploy_mindmap_after_save() -> dict:
    files = collect_data_files()
    return deploy_to_thegospel(files)


if __name__ == "__main__":
    result = deploy_to_thegospel()
    if result.get("ok"):
        print(f"OK {result.get('url')} ({len(result.get('files') or [])} files)")
    else:
        print("FAILED:", result.get("error"))
        raise SystemExit(1)
